export enum BaseType {
  GLOBAL_DB_CONTEXT = 'GLOBAL_DB_CONTEXT',
  DATA_SOURCE = 'DATA_SOURCE',
}

export enum UseCaseType {
  GET_ALL_USERS = 'GET_ALL_USERS',
  GET_USER_BY_EMAIL = 'GET_USER_BY_EMAIL',
  REGISTER_USER = 'REGISTER_USER',

  GET_ALL_ARTICLES = 'GET_ALL_ARTICLES',
  DELETE_USER_ARTICLES = 'DELETE_USER_ARTICLES',
  GET_USER_ARTICLES = 'GET_USER_ARTICLES',
  CREATE_NEW_ARTICLE = 'CREATE_NEW_ARTICLE',
}
